language: java
sudo: false

addons:
  sonarcloud:
    organization: "thiagogarbazza-github"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - mvn clean

install:
  - mvn compile

script:
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'